name: CI

on: [pull_request, push]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v6
    - run: echo system-features = nixos-test >> ~/.config/nix/nix.conf
    - uses: cachix/cachix-action@v3
      with:
        name: 573-ci
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
